### ISSUE TITLE
NavMeshAgentGetAreaMask.cs

### ISSUE THREAD

**Issue by djaydino** [PlayMakerEcosystem/PlayMakerCustomActions_U5#8]
[NavMeshAgentGetAreaMask.cs](https://github.com/PlayMakerEcosystem/PlayMakerCustomActions_U5/blob/master/Assets/PlayMaker%20Custom%20Actions/Navigation/NavMeshAgentGetAreaMask.cs)

On line 71 there is a bool variable which is never used, but it might be needed for the action.

action feels incomplete

**Comment by jeanfabre** [comment]
Hi,

 yes, the bool is not needed. As for the completeness of the action, I don't know, I never used it. but it seems to be doing what it says it does.
